

backend:
  name: github
  repo: CarloBu/animation-tutorial-hub
  branch: main
  base_url: http://localhost:4321
  auth_endpoint: /api/auth

media_folder: public/videos
public_folder: /videos

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: tutorialList
    label: Tutorial List
    create: true
    delete: false
    icon: school
    format: json
    extension: json
    files:
      - file: 'src/content/tutorials/tutorials.json'
        label: Tutorial List
        name: tutorialListFile
        widget: object
        fields:
          - label: Tutorial Items
            name: tutorialItems
            widget: list
            fields:
              - {label: Video, name: src, widget: file}
              - label: Category
                name: category
                dropdown_threshold: 10
                widget: relation
                collection: categoryCollection
                file: categoryListFile
                value_field: "categories.*.category"
                multiple: true

  - name: categoryCollection
    label: Categories
    create: true
    delete: true
    files:
      - file: 'src/content/categories/categories.json'
        label: Category List
        name: categoryListFile
        widget: object
        fields:
          - label: Categories
            name: categories
            widget: list
            fields:
              - {label: Category, name: category, widget: string}