

backend:
  name: github
  repo: CarloBu/animation-tutorial-hub
  branch: main
  base_url: http://localhost:4321
  auth_endpoint: /api/auth

media_folder: public/videos
public_folder: /videos

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - label: Tutorials
    name: tutorials
    create: true
    delete: false
    icon: school
    format: json
    extension: json
    files:
      - file: 'src/content/tutorials/tutorials.json'
        label: Tutorial List
        name: tutorialList
        widget: object
        fields:
          - label: Tutorial
            name: tutorial
            widget: list
            fields:
              - {label: Video, name: src, widget: file}
              - {label: Category, dropdown_threshold: 10, name: category, widget: relation, collection: categories, multiple: true, value_field: category}      

  - name: categories
    label: Categories
    folder: src/content/categories
    create: true
    icon: dashboard_customize
    format: json
    extension: json
    slug: '{{category}}'
    summary: "{{category | category}} - {{order | order }}"
    editor:
      preview: false
    fields:
      - name: category
        label: Category
        widget: string
      - name: order
        label: Order
        widget: number
